#!/bin/bash -exu

export DISABLE_DATABASE_ENVIRONMENT_CHECK=1

./scripts/bundle

cd datalayer

for env in development test; do
  RAILS_ENV=$env bundle exec rails db:drop db:create || true
  RAILS_ENV=$env bundle exec rake db:migrate VERSION=340
  RAILS_ENV=$env bundle exec rake db:migrate
  RAILS_ENV=$env bundle exec rake db:pg:truncate_tables db:pg:data:restore FILE=db/seeds.pgbin
  RAILS_ENV=$env bundle exec rake db:migrate
done
